---
- name: Install packages on Azure VM
  hosts: azure_vm
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Htop
      apt:
        name: htop
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present
