---
- name: Configure Azure VM
  hosts: azure_vms
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Htop
      apt:
        name: htop
        state: present

    - name: Install Curl
      apt:
        name: curl
        state: present

    - name: Create a new user Vibin
      user:
        name: vibin_new
        shell: /bin/bash
        create_home: yes
